//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMDS_DALlib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UmdsDBEntities : DbContext
    {
        public UmdsDBEntities()
            : base("name=UmdsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<NGO> NGOes { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<FinalRequest> FinalRequests { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
    }
}
